title: rpi-pir-motion-sensors
hero_image: images/banner.png
subtitle: rpi-pir-motion-sensors subtitle
description: rpi-pir-motion-sensors description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: PIR Motion Sensors
    duration: 60
